export const relocationSites = [
  {
    "id": "SITE-001",
    "name": "ASDMA-directed safe shelters (statewide, 8 districts)",
    "district": "Cachar",
    "state": "Assam",
    "lat": 24.82407,
    "lng": 92.80062,
    "capacity": 500,
    "availableCapacity": 500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter (directive stage)"
  },
  {
    "id": "SITE-002",
    "name": "Illustrative shelter model (per landslide-prone district)",
    "district": "Cachar",
    "state": "Assam",
    "lat": 24.82407,
    "lng": 92.80062,
    "capacity": 300,
    "availableCapacity": 300,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter (modeled)"
  },
  {
    "id": "SITE-003",
    "name": "Belgaria Township",
    "district": "Dhanbad",
    "state": "Jharkhand",
    "lat": 23.75759,
    "lng": 86.46499,
    "capacity": 11000,
    "availableCapacity": 11000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relocation Colony"
  },
  {
    "id": "SITE-004",
    "name": "Karmatand Rehabilitation Site",
    "district": "Dhanbad",
    "state": "Jharkhand",
    "lat": 23.795663,
    "lng": 86.430375,
    "capacity": 20040,
    "availableCapacity": 20040,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relocation Colony"
  },
  {
    "id": "SITE-005",
    "name": "Udhwa Block Flood Shelter (model)",
    "district": "Sahibganj",
    "state": "Jharkhand",
    "lat": 25.244252,
    "lng": 87.634814,
    "capacity": 300,
    "availableCapacity": 300,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-006",
    "name": "Rajmahal Block Flood Shelter (model)",
    "district": "Sahibganj",
    "state": "Jharkhand",
    "lat": 25.244252,
    "lng": 87.634814,
    "capacity": 300,
    "availableCapacity": 300,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-007",
    "name": "Pakur District Flood Shelter (model)",
    "district": "Pakur",
    "state": "Jharkhand",
    "lat": 24.637906,
    "lng": 87.855696,
    "capacity": 350,
    "availableCapacity": 350,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-008",
    "name": "Godda District Flood Shelter (model)",
    "district": "Godda",
    "state": "Jharkhand",
    "lat": 24.827778,
    "lng": 87.211388,
    "capacity": 300,
    "availableCapacity": 300,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-009",
    "name": "East Singhbhum District Flood Shelter (model)",
    "district": "Purbi Singhbhum",
    "state": "Jharkhand",
    "lat": 22.813211,
    "lng": 86.168844,
    "capacity": 400,
    "availableCapacity": 400,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-010",
    "name": "West Singhbhum District Flood Shelter (model)",
    "district": "Pashchimi Singhbhum",
    "state": "Jharkhand",
    "lat": 22.550377,
    "lng": 85.802489,
    "capacity": 350,
    "availableCapacity": 350,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-011",
    "name": "Garhwa District Flood Shelter (model)",
    "district": "Garhwa",
    "state": "Jharkhand",
    "lat": 24.160021,
    "lng": 83.807546,
    "capacity": 300,
    "availableCapacity": 300,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-012",
    "name": "Palamu District Flood Shelter (model)",
    "district": "Palamu",
    "state": "Jharkhand",
    "lat": 24.04,
    "lng": 84.07,
    "capacity": 300,
    "availableCapacity": 300,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-013",
    "name": "Gumla District Flood Shelter (model)",
    "district": "Gumla",
    "state": "Jharkhand",
    "lat": 23.080546,
    "lng": 84.538339,
    "capacity": 300,
    "availableCapacity": 300,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-014",
    "name": "Simdega District Flood Shelter (model)",
    "district": "Simdega",
    "state": "Jharkhand",
    "lat": 22.615226,
    "lng": 84.502079,
    "capacity": 250,
    "availableCapacity": 250,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-015",
    "name": "Muttathara Complex",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "lat": 8.46744,
    "lng": 76.93857,
    "capacity": 1328,
    "availableCapacity": 1328,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relocation Colony"
  },
  {
    "id": "SITE-016",
    "name": "Karode Flats",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "lat": 8.401654,
    "lng": 77.087114,
    "capacity": 512,
    "availableCapacity": 512,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relocation Colony"
  },
  {
    "id": "SITE-017",
    "name": "Valiyathura Flats",
    "district": "Thiruvananthapuram",
    "state": "Kerala",
    "lat": 8.4646,
    "lng": 76.9276,
    "capacity": 768,
    "availableCapacity": 768,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relocation Colony"
  },
  {
    "id": "SITE-018",
    "name": "Beemapally & QSS Colony Flats",
    "district": "Kollam (as stated in source; Beemapally is more commonly located in Thiruvananthapuram - verify locally)",
    "state": "Kerala",
    "lat": 8.887082,
    "lng": 76.590691,
    "capacity": 670,
    "availableCapacity": 670,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relocation Colony"
  },
  {
    "id": "SITE-019",
    "name": "Ponnani Flats",
    "district": "Malappuram",
    "state": "Kerala",
    "lat": 10.7801,
    "lng": 75.9189,
    "capacity": 512,
    "availableCapacity": 512,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relocation Colony"
  },
  {
    "id": "SITE-020",
    "name": "Mannumpuram Flats",
    "district": "Alappuzha",
    "state": "Kerala",
    "lat": 9.35351,
    "lng": 76.36525,
    "capacity": 912,
    "availableCapacity": 912,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relocation Colony"
  },
  {
    "id": "SITE-021",
    "name": "Unniyal (Tanur) Flats",
    "district": "Malappuram",
    "state": "Kerala",
    "lat": 10.91941,
    "lng": 75.88691,
    "capacity": 64,
    "availableCapacity": 64,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relocation Colony"
  },
  {
    "id": "SITE-022",
    "name": "Illustrative shelter model (per hill district)",
    "district": "Tamenglong",
    "state": "Manipur",
    "lat": 24.97548,
    "lng": 93.51563,
    "capacity": 250,
    "availableCapacity": 250,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter (modeled)"
  },
  {
    "id": "SITE-023",
    "name": "Bagapatia Rehabilitation Colony",
    "district": "Kendrapara",
    "state": "Odisha",
    "lat": 20.673056,
    "lng": 86.89,
    "capacity": 2855,
    "availableCapacity": 2855,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relocation Colony"
  },
  {
    "id": "SITE-024",
    "name": "Kendrapara district shelter network (117 listed)",
    "district": "Kendrapara",
    "state": "Odisha",
    "lat": 20.501662,
    "lng": 86.422267,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter network"
  },
  {
    "id": "SITE-025",
    "name": "Statewide Multipurpose Cyclone Shelter (MCS) network",
    "district": "All coastal districts (Ganjam",
    "state": "Odisha",
    "lat": 20.296059,
    "lng": 85.824539,
    "capacity": 1000000,
    "availableCapacity": 1000000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter network"
  },
  {
    "id": "SITE-026",
    "name": "ICZMP shelter tranche (14 shelters)",
    "district": "Kendrapara (4)",
    "state": "Odisha",
    "lat": 20.501662,
    "lng": 86.422267,
    "capacity": 500,
    "availableCapacity": 500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter (named tranche)"
  },
  {
    "id": "SITE-JHGEO-001",
    "name": "S.D.O Office Sahibganj",
    "district": "Sahibganj",
    "state": "Jharkhand",
    "lat": 25.243418,
    "lng": 87.648083,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-002",
    "name": "Sadar Hospital Gumla",
    "district": "Gumla",
    "state": "Jharkhand",
    "lat": 23.035556,
    "lng": 84.536944,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-003",
    "name": "Sale Tax Office Sahibganj",
    "district": "Sahibganj",
    "state": "Jharkhand",
    "lat": 25.240653,
    "lng": 87.647042,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-004",
    "name": "Settlement Office",
    "district": "Palamu",
    "state": "Jharkhand",
    "lat": 24.0401,
    "lng": 84.070981,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-005",
    "name": "Circuit House Gumla",
    "district": "Gumla",
    "state": "Jharkhand",
    "lat": 23.0385,
    "lng": 84.534333,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-006",
    "name": "SDM Office",
    "district": "Pakur",
    "state": "Jharkhand",
    "lat": 24.63831,
    "lng": 87.835427,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-007",
    "name": "Collectorate Building",
    "district": "Palamu",
    "state": "Jharkhand",
    "lat": 24.039264,
    "lng": 84.070714,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-013",
    "name": "SNMMCH Dhanbad",
    "district": "Dhanbad",
    "state": "Jharkhand",
    "lat": 23.4831,
    "lng": 86.2744,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-017",
    "name": "12 Court Building",
    "district": "Pakur",
    "state": "Jharkhand",
    "lat": 24.636289,
    "lng": 87.836205,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-019",
    "name": "B2 Block (1 Block 6 Unit)",
    "district": "Deoghar",
    "state": "Jharkhand",
    "lat": 24.490278,
    "lng": 86.678056,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-020",
    "name": "6 P.O. Qtr, Hirna",
    "district": "Deoghar",
    "state": "Jharkhand",
    "lat": 24.490833,
    "lng": 86.678889,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-024",
    "name": "S.D.M. Residence, Hazaribag",
    "district": "Hazaribag",
    "state": "Jharkhand",
    "lat": 24.008333,
    "lng": 85.359722,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-025",
    "name": "E.V.M. Warehouse, Hazaribag",
    "district": "Hazaribag",
    "state": "Jharkhand",
    "lat": 24.014444,
    "lng": 85.355278,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-028",
    "name": "Circuit House, Lohardaga.",
    "district": "Lohardaga",
    "state": "Jharkhand",
    "lat": 23.450278,
    "lng": 84.705,
    "capacity": 100,
    "availableCapacity": 100,
    "status": "AVAILABLE",
    "siteType": "government_building"
  },
  {
    "id": "SITE-JHGEO-048",
    "name": "Mahuatand",
    "district": "Bokaro",
    "state": "Jharkhand",
    "lat": 23.696,
    "lng": 85.675,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-050",
    "name": "Morbey",
    "district": "Garhwa",
    "state": "Jharkhand",
    "lat": 24.398906,
    "lng": 83.834132,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-051",
    "name": "Sadam",
    "district": "Bokaro",
    "state": "Jharkhand",
    "lat": 23.755,
    "lng": 85.824,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-060",
    "name": "Balalong",
    "district": "Ranchi",
    "state": "Jharkhand",
    "lat": 23.3075,
    "lng": 85.237778,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-061",
    "name": "Dahu",
    "district": "Ranchi",
    "state": "Jharkhand",
    "lat": 23.480556,
    "lng": 85.444167,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-062",
    "name": "Danda",
    "district": "Garhwa",
    "state": "Jharkhand",
    "lat": 24.146222,
    "lng": 83.944344,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-064",
    "name": "Rudra Hospital",
    "district": "East Singhbhum",
    "state": "Jharkhand",
    "lat": 22.750589,
    "lng": 86.203878,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-067",
    "name": "Asansol",
    "district": "Dumka",
    "state": "Jharkhand",
    "lat": 24.227222,
    "lng": 87.2725,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-069",
    "name": "Matrika sadan",
    "district": "Ramgarh",
    "state": "Jharkhand",
    "lat": 23.584081,
    "lng": 85.635178,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-072",
    "name": "BADAM",
    "district": "Hazaribagh",
    "state": "Jharkhand",
    "lat": 23.841,
    "lng": 85.286,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-073",
    "name": "CAPTAIN HOSPITAL, THARA TOLI",
    "district": "Lohardaga",
    "state": "Jharkhand",
    "lat": 23.43583,
    "lng": 84.67972,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-074",
    "name": "GOURIYA KARMA",
    "district": "Hazaribagh",
    "state": "Jharkhand",
    "lat": 24.278,
    "lng": 85.349,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-076",
    "name": "Baba Ashram",
    "district": "Saraikela",
    "state": "Jharkhand",
    "lat": 22.831412,
    "lng": 86.123403,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-077",
    "name": "Purnima Netralaya",
    "district": "Saraikela",
    "state": "Jharkhand",
    "lat": 22.781042,
    "lng": 86.163167,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-083",
    "name": "Dr. Rajdev",
    "district": "Jamtara",
    "state": "Jharkhand",
    "lat": 23.968136,
    "lng": 86.804458,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-087",
    "name": "Smriti Seva Sadan",
    "district": "East Singhbhum",
    "state": "Jharkhand",
    "lat": 22.815692,
    "lng": 86.174075,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-103",
    "name": "Salgapogh",
    "district": "Simdega",
    "state": "Jharkhand",
    "lat": 22.445,
    "lng": 84.414722,
    "capacity": 150,
    "availableCapacity": 150,
    "status": "AVAILABLE",
    "siteType": "hospital"
  },
  {
    "id": "SITE-JHGEO-109",
    "name": "Sahebganj Rail",
    "district": "Rail Dhanbad",
    "state": "Jharkhand",
    "lat": 25.239224,
    "lng": 87.634248,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-JHGEO-112",
    "name": "SIDHGORA",
    "district": "Jamshedpur",
    "state": "Jharkhand",
    "lat": 22.799418,
    "lng": 86.23453,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-JHGEO-113",
    "name": "NARAYANPUR",
    "district": "Jamtara",
    "state": "Jharkhand",
    "lat": 24.043066,
    "lng": 86.616004,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-JHGEO-115",
    "name": "GOLMURI TRAFFIC P.S",
    "district": "Jamshedpur",
    "state": "Jharkhand",
    "lat": 22.793665,
    "lng": 86.223612,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-JHGEO-117",
    "name": "NIRSA",
    "district": "Dhanbad",
    "state": "Jharkhand",
    "lat": 23.787634,
    "lng": 86.703478,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-JHGEO-118",
    "name": "MANIKA",
    "district": "Latehar",
    "state": "Jharkhand",
    "lat": 23.855709,
    "lng": 84.353091,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-JHGEO-122",
    "name": "MAYURHUNT",
    "district": "Chatra",
    "state": "Jharkhand",
    "lat": 24.29447,
    "lng": 85.241232,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-JHGEO-123",
    "name": "JHIKPANI",
    "district": "Chaibasa",
    "state": "Jharkhand",
    "lat": 22.421871,
    "lng": 85.774413,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-JHGEO-140",
    "name": "HUNTERGUNJ",
    "district": "Chatra",
    "state": "Jharkhand",
    "lat": 24.434112,
    "lng": 84.810878,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-JHGEO-142",
    "name": "SUNDERPAHARI",
    "district": "Godda",
    "state": "Jharkhand",
    "lat": 24.757229,
    "lng": 87.351221,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-JHGEO-145",
    "name": "PORAIYAHAT",
    "district": "Godda",
    "state": "Jharkhand",
    "lat": 24.674368,
    "lng": 87.170247,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-JHGEO-151",
    "name": "SARIYA",
    "district": "Giridih",
    "state": "Jharkhand",
    "lat": 24.172607,
    "lng": 85.8797,
    "capacity": 80,
    "availableCapacity": 80,
    "status": "AVAILABLE",
    "siteType": "police_station"
  },
  {
    "id": "SITE-027",
    "name": "Meppadi Safe Relief Camp & Higher Secondary Complex",
    "district": "Wayanad",
    "state": "Kerala",
    "lat": 11.551,
    "lng": 76.128,
    "capacity": 2500,
    "availableCapacity": 2500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-028",
    "name": "Kalpetta Municipal Safe Relief Center",
    "district": "Wayanad",
    "state": "Kerala",
    "lat": 11.6083,
    "lng": 76.085,
    "capacity": 4000,
    "availableCapacity": 4000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Multi-Purpose Shelter"
  },
  {
    "id": "SITE-029",
    "name": "Pipalkoti Rehabilitation Township",
    "district": "Chamoli",
    "state": "Uttarakhand",
    "lat": 30.43,
    "lng": 79.43,
    "capacity": 4500,
    "availableCapacity": 4500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relocation Colony"
  },
  {
    "id": "SITE-030",
    "name": "Gauchar Disaster Relief & Transit Complex",
    "district": "Chamoli",
    "state": "Uttarakhand",
    "lat": 30.29,
    "lng": 79.16,
    "capacity": 3000,
    "availableCapacity": 3000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-031",
    "name": "Kakdwip Multi-Purpose Cyclone Shelter",
    "district": "South 24 Parganas",
    "state": "West Bengal",
    "lat": 21.876,
    "lng": 88.188,
    "capacity": 5000,
    "availableCapacity": 5000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Multi-Purpose Cyclone Shelter"
  },
  {
    "id": "SITE-032",
    "name": "Namkhana Central Cyclone Rehabilitation Center",
    "district": "South 24 Parganas",
    "state": "West Bengal",
    "lat": 21.768,
    "lng": 88.235,
    "capacity": 6500,
    "availableCapacity": 6500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-033",
    "name": "Mandi District Sports Complex Shelter",
    "district": "Mandi",
    "state": "Himachal Pradesh",
    "lat": 31.7087,
    "lng": 76.932,
    "capacity": 3500,
    "availableCapacity": 3500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-034",
    "name": "Dhalpur Relief Transit Center",
    "district": "Kullu",
    "state": "Himachal Pradesh",
    "lat": 31.9578,
    "lng": 77.1095,
    "capacity": 4000,
    "availableCapacity": 4000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-035",
    "name": "ASDMA Silchar District Sports Stadium Relief Camp",
    "district": "Cachar",
    "state": "Assam",
    "lat": 24.8333,
    "lng": 92.7789,
    "capacity": 4500,
    "availableCapacity": 4500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-036",
    "name": "Haflong Higher Secondary School Safe Shelter",
    "district": "Dima Hasao",
    "state": "Assam",
    "lat": 25.178,
    "lng": 93.021,
    "capacity": 2500,
    "availableCapacity": 2500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-037",
    "name": "Noney District Headquarters Safe Relief Camp",
    "district": "Noney",
    "state": "Manipur",
    "lat": 24.785,
    "lng": 93.605,
    "capacity": 2500,
    "availableCapacity": 2500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-038",
    "name": "Khurai Indoor Hall Safe Relief Facility",
    "district": "Imphal East",
    "state": "Manipur",
    "lat": 24.817,
    "lng": 93.955,
    "capacity": 5000,
    "availableCapacity": 5000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-039",
    "name": "Guptkashi Safe Evacuation & Relief Center",
    "district": "Rudraprayag",
    "state": "Uttarakhand",
    "lat": 30.52,
    "lng": 79.08,
    "capacity": 3500,
    "availableCapacity": 3500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Multi-Purpose Relief Hub"
  },
  {
    "id": "SITE-040",
    "name": "Agastyamuni District Sports Ground Safe Shelter",
    "district": "Rudraprayag",
    "state": "Uttarakhand",
    "lat": 30.39,
    "lng": 78.98,
    "capacity": 4500,
    "availableCapacity": 4500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Center"
  },
  {
    "id": "SITE-041",
    "name": "Hari Niwas Safe Relief Hub (High-Altitude Zone)",
    "district": "Srinagar",
    "state": "Jammu and Kashmir",
    "lat": 34.09,
    "lng": 74.86,
    "capacity": 6000,
    "availableCapacity": 6000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Highland Relief Complex"
  },
  {
    "id": "SITE-042",
    "name": "Anantnag Degree College Sports Relief Campus",
    "district": "Anantnag",
    "state": "Jammu and Kashmir",
    "lat": 33.74,
    "lng": 75.14,
    "capacity": 6500,
    "availableCapacity": 6500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-043",
    "name": "Tambaram Sanatorium Government Relief Complex",
    "district": "Chengalpattu",
    "state": "Tamil Nadu",
    "lat": 12.935,
    "lng": 80.14,
    "capacity": 8000,
    "availableCapacity": 8000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Elevated Hospital Relief Center"
  },
  {
    "id": "SITE-044",
    "name": "Guindy Race Course High-Elevation Relief Camp",
    "district": "Chennai",
    "state": "Tamil Nadu",
    "lat": 13.005,
    "lng": 80.21,
    "capacity": 9000,
    "availableCapacity": 9000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Center"
  },
  {
    "id": "SITE-045",
    "name": "Brahmagiri Multi-Purpose Cyclone Shelter",
    "district": "Puri",
    "state": "Odisha",
    "lat": 19.8,
    "lng": 85.68,
    "capacity": 5500,
    "availableCapacity": 5500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Multi-Purpose Cyclone Shelter"
  },
  {
    "id": "SITE-046",
    "name": "Puri Town Central Relief Complex",
    "district": "Puri",
    "state": "Odisha",
    "lat": 19.82,
    "lng": 85.83,
    "capacity": 7000,
    "availableCapacity": 7000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-047",
    "name": "Manchar Elevated Relief Complex (Ambegaon)",
    "district": "Pune",
    "state": "Maharashtra",
    "lat": 19.005,
    "lng": 73.94,
    "capacity": 3000,
    "availableCapacity": 3000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Permanent Relocation Township"
  },
  {
    "id": "SITE-048",
    "name": "Mahad Industrial Complex Disaster Safe Shelter",
    "district": "Raigad",
    "state": "Maharashtra",
    "lat": 18.08,
    "lng": 73.43,
    "capacity": 3500,
    "availableCapacity": 3500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Center"
  },
  {
    "id": "SITE-049",
    "name": "Supaul District High School Disaster Relief Complex",
    "district": "Supaul",
    "state": "Bihar",
    "lat": 26.12,
    "lng": 86.6,
    "capacity": 7500,
    "availableCapacity": 7500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Elevated Flood Shelter"
  },
  {
    "id": "SITE-050",
    "name": "Saharsa Stadium Relief Transit Camp",
    "district": "Saharsa",
    "state": "Bihar",
    "lat": 25.88,
    "lng": 86.6,
    "capacity": 7000,
    "availableCapacity": 7000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Center"
  },
  {
    "id": "SITE-051",
    "name": "Mangan District Administration Elevated Relief Hub",
    "district": "Mangan",
    "state": "Sikkim",
    "lat": 27.5,
    "lng": 88.53,
    "capacity": 3000,
    "availableCapacity": 3000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Mountain Relief Complex"
  },
  {
    "id": "SITE-052",
    "name": "Gangtok Paljor Stadium Safe Relief Facility",
    "district": "Gangtok",
    "state": "Sikkim",
    "lat": 27.33,
    "lng": 88.61,
    "capacity": 4500,
    "availableCapacity": 4500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Multi-Purpose Relief Hub"
  },
  {
    "id": "SITE-053",
    "name": "Rajula Multi-Purpose Cyclone Shelter",
    "district": "Amreli",
    "state": "Gujarat",
    "lat": 20.95,
    "lng": 71.44,
    "capacity": 6000,
    "availableCapacity": 6000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Multi-Purpose Cyclone Shelter"
  },
  {
    "id": "SITE-054",
    "name": "Bhuj Disaster Management Transit Complex",
    "district": "Kutch",
    "state": "Gujarat",
    "lat": 23.24,
    "lng": 69.66,
    "capacity": 7500,
    "availableCapacity": 7500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Center"
  },
  {
    "id": "SITE-055",
    "name": "Indira Gandhi Municipal Stadium Relief Center",
    "district": "NTR",
    "state": "Andhra Pradesh",
    "lat": 16.505,
    "lng": 80.65,
    "capacity": 9000,
    "availableCapacity": 9000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Mega Relief Hub"
  },
  {
    "id": "SITE-056",
    "name": "Bapatla Engineering College Safe Relief Center",
    "district": "Bapatla",
    "state": "Andhra Pradesh",
    "lat": 15.91,
    "lng": 80.45,
    "capacity": 5000,
    "availableCapacity": 5000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Cyclone Shelter"
  },
  {
    "id": "SITE-057",
    "name": "Chromepet Disaster Relief & Medical Center",
    "district": "Chengalpattu",
    "state": "Tamil Nadu",
    "lat": 12.952,
    "lng": 80.141,
    "capacity": 7000,
    "availableCapacity": 7000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Center"
  },
  {
    "id": "SITE-058",
    "name": "Panvel Disaster Management Transit Camp",
    "district": "Raigad",
    "state": "Maharashtra",
    "lat": 18.99,
    "lng": 73.11,
    "capacity": 5000,
    "availableCapacity": 5000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Transit Camp"
  },
  {
    "id": "SITE-059",
    "name": "Srinagar Garhwal High-Ground Relief Complex",
    "district": "Pauri Garhwal",
    "state": "Uttarakhand",
    "lat": 30.22,
    "lng": 78.78,
    "capacity": 6000,
    "availableCapacity": 6000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Mega Relief Hub"
  },
  {
    "id": "SITE-060",
    "name": "Rudraprayag Sports Stadium Relief Shelter",
    "district": "Rudraprayag",
    "state": "Uttarakhand",
    "lat": 30.28,
    "lng": 78.98,
    "capacity": 4000,
    "availableCapacity": 4000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Shelter"
  },
  {
    "id": "SITE-061",
    "name": "Chamoli District Headquarters Transit Hub",
    "district": "Chamoli",
    "state": "Uttarakhand",
    "lat": 30.405,
    "lng": 79.325,
    "capacity": 5000,
    "availableCapacity": 5000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Transit Hub"
  },
  {
    "id": "SITE-062",
    "name": "Sarusajai Stadium Mega Relief Complex (Guwahati)",
    "district": "Kamrup Metropolitan",
    "state": "Assam",
    "lat": 26.115,
    "lng": 91.765,
    "capacity": 12000,
    "availableCapacity": 12000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Mega Relief Hub"
  },
  {
    "id": "SITE-063",
    "name": "Jorhat District Multi-Purpose Flood Shelter",
    "district": "Jorhat",
    "state": "Assam",
    "lat": 26.75,
    "lng": 94.22,
    "capacity": 5000,
    "availableCapacity": 5000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Multi-Purpose Shelter"
  },
  {
    "id": "SITE-064",
    "name": "Dhemaji Town Elevated Disaster Relief Campus",
    "district": "Dhemaji",
    "state": "Assam",
    "lat": 27.48,
    "lng": 94.57,
    "capacity": 4500,
    "availableCapacity": 4500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Elevated Flood Shelter"
  },
  {
    "id": "SITE-065",
    "name": "Kamrup District Rural Safe Shelter Network",
    "district": "Kamrup",
    "state": "Assam",
    "lat": 26.31,
    "lng": 91.6,
    "capacity": 6000,
    "availableCapacity": 6000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Center"
  },
  {
    "id": "SITE-066",
    "name": "Churachandpur District Safe Evacuation Hub",
    "district": "Churachandpur",
    "state": "Manipur",
    "lat": 24.33,
    "lng": 93.68,
    "capacity": 4000,
    "availableCapacity": 4000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Center"
  },
  {
    "id": "SITE-067",
    "name": "Tamenglong Higher Secondary Safe Camp",
    "district": "Tamenglong",
    "state": "Manipur",
    "lat": 24.99,
    "lng": 93.5,
    "capacity": 3000,
    "availableCapacity": 3000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Camp"
  },
  {
    "id": "SITE-068",
    "name": "Kangpokpi Community Relief Facility",
    "district": "Kangpokpi",
    "state": "Manipur",
    "lat": 25.15,
    "lng": 93.97,
    "capacity": 3500,
    "availableCapacity": 3500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Center"
  },
  {
    "id": "SITE-069",
    "name": "Bishnupur Indoor Stadium Relief Complex",
    "district": "Bishnupur",
    "state": "Manipur",
    "lat": 24.63,
    "lng": 93.76,
    "capacity": 4500,
    "availableCapacity": 4500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Hub"
  },
  {
    "id": "SITE-070",
    "name": "Sulthan Bathery Multi-Purpose Disaster Camp",
    "district": "Wayanad",
    "state": "Kerala",
    "lat": 11.66,
    "lng": 76.26,
    "capacity": 4000,
    "availableCapacity": 4000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Center"
  },
  {
    "id": "SITE-071",
    "name": "Mananthavady Municipal Relief Complex",
    "district": "Wayanad",
    "state": "Kerala",
    "lat": 11.8,
    "lng": 76.0,
    "capacity": 4500,
    "availableCapacity": 4500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Relief Hub"
  },
  {
    "id": "SITE-072",
    "name": "Alappuzha SDV High School Flood Relief Hub",
    "district": "Alappuzha",
    "state": "Kerala",
    "lat": 9.49,
    "lng": 76.33,
    "capacity": 6000,
    "availableCapacity": 6000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Mega Relief Hub"
  },
  {
    "id": "SITE-073",
    "name": "Chengannur Engineering College Flood Camp",
    "district": "Alappuzha",
    "state": "Kerala",
    "lat": 9.317,
    "lng": 76.617,
    "capacity": 5000,
    "availableCapacity": 5000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Elevated Flood Shelter"
  },
  {
    "id": "SITE-074",
    "name": "Kozhikode Indoor Stadium Relief Hub",
    "district": "Kozhikode",
    "state": "Kerala",
    "lat": 11.2588,
    "lng": 75.7804,
    "capacity": 7000,
    "availableCapacity": 7000,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Mega Relief Center"
  },
  {
    "id": "SITE-075",
    "name": "Prayagraj University Science Campus Elevated Shelter",
    "district": "Prayagraj",
    "state": "Uttar Pradesh",
    "lat": 25.459,
    "lng": 81.854,
    "capacity": 8500,
    "availableCapacity": 8500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Elevated University Complex"
  },
  {
    "id": "SITE-076",
    "name": "Gwalior District Sports Stadium Safe Relief Complex",
    "district": "Gwalior",
    "state": "Madhya Pradesh",
    "lat": 26.218,
    "lng": 78.182,
    "capacity": 9500,
    "availableCapacity": 9500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Mega Sports Complex Shelter"
  },
  {
    "id": "SITE-077",
    "name": "Barpeta Town High-Ground Relief Center",
    "district": "Barpeta",
    "state": "Assam",
    "lat": 26.352,
    "lng": 91.025,
    "capacity": 7500,
    "availableCapacity": 7500,
    "status": "AVAILABLE",
    "siteType": "Safe Site / Elevated Multi-Purpose Safe Shelter"
  }
];
